### ISSUE TITLE
Error starting OAuth flow:

### ISSUE THREAD

**Issue by NewsThisSecond** [MitchellMcKenna/twitter-rss-google-apps-script#10]
Error starting OAuth flow: <?xml version="1.0" encoding="UTF-8"?>
<hash>
  <error>Desktop applications only support the oauth_callback value 'oob'</error>
  <request>/oauth/request_token</request>
</hash>

**Comment by NewsThisSecond** [comment]
[18-04-23 14:18:24:307 BST] Error starting OAuth flow: <?xml version="1.0" encoding="UTF-8"?>
<hash>
  <error>Desktop applications only support the oauth_callback value 'oob'</error>
  <request>/oauth/request_token</request>
</hash>

**Comment by mruac** [comment]
I encountered this issue too; it is to do with Twitter's stricter callback URL requirements. Simply pointing to a google domain does not work anymore. See #11 for the solution.
